import {
  AlertCircle,
  Calendar,
  CheckSquare,
  Command,
  FileText,
  Folder,
  Gavel,
  HelpCircle,
  Inbox,
  Info,
  Lightbulb,
  Redo2,
  RefreshCw,
  Search,
  Settings,
  Sun,
  Moon,
  Monitor,
  Undo2,
  Users,
  User,
  Zap,
  type LucideIcon,
} from 'lucide-react';

const iconMap: Record<string, LucideIcon> = {
  'check-square': CheckSquare,
  'help-circle': HelpCircle,
  info: Info,
  user: User,
  folder: Folder,
  calendar: Calendar,
  users: Users,
  gavel: Gavel,
  lightbulb: Lightbulb,
  'file-text': FileText,
  inbox: Inbox,
  'alert-circle': AlertCircle,
  refresh: RefreshCw,
  settings: Settings,
  sun: Sun,
  moon: Moon,
  monitor: Monitor,
  search: Search,
  undo: Undo2,
  redo: Redo2,
  zap: Zap,
  command: Command,
};

export function getIcon(name: string): LucideIcon {
  return iconMap[name] ?? FileText;
}
